### ISSUE TITLE
Prefix class names with `filter-`?

### ISSUE THREAD

**Issue by tomByrer** [una/CSSgram#159]
Advantages:
+ prevents an onboarding devs say "What the ___ is 'hudson'?"
+ allows global search/replace/delete

Disadvantages:
- larger files (mostly negated by gzip)
- more typing (reduced by editors' autocomplete, copy/paste|search/replace
- add extra coding to `gulpfile`

Could prefix with `cssgram-` also, less clear, but helps in finding this repo.

**Comment by redaxmedia** [comment]
1+

**Comment by una** [comment]
Hey @tomByrer -- I agree with namespacing being a good idea for semantic understanding. My biggest concern with this is that it would be a breaking change to the previous workflow and would affect everyone who has already implemented the library. The question here is -- is that tradeoff worth it?

**Comment by Effeilo** [comment]
1+ 
Another advantage, it will ease the code. for example

````css

[class*="cssgram-"] {
  position: relative;
}

[class*="cssgram-"]:before, 
[class*="cssgram-"]:after {
  content: '';
  display: block;
  height: 100%;
  width: 100%;
  top: 0;
  left: 0;
  position: absolute;
  pointer-events: none;
}

[class*="cssgram-"] > img {
  width: 100%;
  z-index: 1;
}

[class*="cssgram-"]:before {
  z-index: 2;
}

[class*="cssgram-"]:after {
  z-index: 3;
}
````
